apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
type: Opaque
stringData:
  SA_PASSWORD: "Password123!"
  CONNECTION_STRING: "Server=sqlserver-service;Database=BookingDB;User Id=sa;Password=Password123!;TrustServerCertificate=True;MultipleActiveResultSets=true"