apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
type: Opaque
stringData:
  SA_PASSWORD: "CHANGE_ME"
  CONNECTION_STRING: "Server=sqlserver-service;Database=BookingDB;User Id=sa;Password=CHANGE_ME;TrustServerCertificate=True;MultipleActiveResultSets=true"